# Change these first
owner: ModSuiteCloud # Your GitHub organization or username, where this repository lives
repo: modsuite-status # The name of this repository

sites:
  - name: ModSuite Website
    url: https://modsuite.cloud
  - name: ModSuite Cloud
    url: https://api.modsuite.cloud/api/v1/hello
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.modsuite.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ModSuite Status
  introTitle: "**ModSuite** Status and uptime monitor."
  introMessage: See below the status of ModSuite services in real-time.
  navbar:
    - title: Go to app
      href: https://modsuite.cloud
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ModSuiteCloud/ModSuite-Status
    - title: Discord
      href: https://discord.gg/yagZvY3ajb

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
